### PR TITLE
Plotting and Quicklooks

### PR DESCRIPTION
**Pull request by ninarobbins**
Plotting scripts for nice post-flight plots and during-flight quicklooks.

Quick gridding is included currently but should be removed in favor of L3 product. The quicklooks should work with the halo drops processing and be able to use the config file.

### CODE REVIEW

**Comment by hgloeckner** [comment]
Thanks for the quicklooks :) It's nice to see what's possible. 

I have a few points: 

- I would not add all the images (if we want some we can do this for one or two quicklooks, but all of them is too much and not the purpose of this repo (from my understanding)
- It would be nice if we didn't have to import more repos that are only half-maintained (i.e. the `from quicklooks import...`). I'd rather have fewer plots, but have them self-contained (obviously importing from pyorcestra is fine) 
- I think it does not make sense to have the same plotting script for each flight. I'd rather have a quicklook script for each plot and a yaml or txt where we have the rough flight segmentation (or have them in the header for the moment)
- we don't need `quickgrid`. Even in flight, the current pydropsonde pipeline does not take more than a few seconds. I would prefer having the quicklooks on the current state of Level3 (or Level2) as long as it is feasible.

So, my preferred structure would be having a droputils folder with a plot_utils.py and a physics.py or similar and then a plots folder with one file (either .py or .ipynb) for one plot at a time. Those could contain a header with an example segmentation for one flight (e.g. 20240811 because it was the first) and we'd have a txt file where we store the other rough segmentations so that people could plug them in if they wish.

**Comment by hgloeckner** [comment]
I added some idea in [my fork](https://github.com/hgloeckner/dropsondes.git) under the orcestra_quicklooks branch. It's by no means perfect, just to illustrate the structure of what I had in mind.

**Comment by ninarobbins** [comment]
Hi @hgloeckner. I agree with your points. Right now this branch is very much in a draft state and I wanted to add everything in there before making it final.

- I thought to have the same structure with one script per flight as in the flight planning, as these will likely not change, but it's a better idea to have a plotting config file with the circle times/date/plotting parameters for each day, and one script that plots based on the config, so that we only have to change the plotting script in one place.
- Quickgrid was only meant as a placeholder, I was using it for easy quick plotting since I knew It had everything needed already. But the goal was always to have this working with halo-drops  L3/L4 data.
- I will put the images in the Quicklooks folder in the ORCESTRA server.

I'm working on these changes.

**Comment by hgloeckner** [comment]
We'll make new pull requests for each plot in the new structure

**Pull request closed without merging**
